/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Mobile mobile=new Mobile();
        mobile.call("message");
        
        Iphone iphone=new Iphone();
        iphone.call("message");
        
        Andriod andriod=new Andriod();
        andriod.call("message");
    }
}
